In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
%matplotlib inline

In [2]:
BBB_Train_Dec0 = pd.read_pickle("BBB_Train_Dec0_ML.pkl")
BBB_Train_Dec1 = pd.read_pickle("BBB_Train_Dec1_ML.pkl")
BBB_Train_Dec2 = pd.read_pickle("BBB_Train_Dec2_ML.pkl")
BBB_Train_Dec3 = pd.read_pickle("BBB_Train_Dec3_ML.pkl")
BBB_Train_Dec4 = pd.read_pickle("BBB_Train_Dec4_ML.pkl")
BBB_Train_Dec5 = pd.read_pickle("BBB_Train_Dec5_ML.pkl")
BBB_Train_Dec6 = pd.read_pickle("BBB_Train_Dec6_ML.pkl")
BBB_Train_Dec7 = pd.read_pickle("BBB_Train_Dec7_ML.pkl")
BBB_Train_Dec8 = pd.read_pickle("BBB_Train_Dec8_ML.pkl")
BBB_Train_Dec9 = pd.read_pickle("BBB_Train_Dec9_ML.pkl")
BBB_Train_Dec10 = pd.read_pickle("BBB_Train_Dec10_ML.pkl")

BBB_Test_Dec0 = pd.read_pickle("BBB_Test_Dec0_ML.pkl")
BBB_Test_Dec1 = pd.read_pickle("BBB_Test_Dec1_ML.pkl")
BBB_Test_Dec2 = pd.read_pickle("BBB_Test_Dec2_ML.pkl")
BBB_Test_Dec3 = pd.read_pickle("BBB_Test_Dec3_ML.pkl")
BBB_Test_Dec4 = pd.read_pickle("BBB_Test_Dec4_ML.pkl")
BBB_Test_Dec5 = pd.read_pickle("BBB_Test_Dec5_ML.pkl")
BBB_Test_Dec6 = pd.read_pickle("BBB_Test_Dec6_ML.pkl")
BBB_Test_Dec7 = pd.read_pickle("BBB_Test_Dec7_ML.pkl")
BBB_Test_Dec8 = pd.read_pickle("BBB_Test_Dec8_ML.pkl")
BBB_Test_Dec9 = pd.read_pickle("BBB_Test_Dec9_ML.pkl")
BBB_Test_Dec10 = pd.read_pickle("BBB_Test_Dec10_ML.pkl")

In [3]:
DDD_Train_Dec0 = pd.read_pickle("DDD_Train_Dec0_ML.pkl")
DDD_Train_Dec1 = pd.read_pickle("DDD_Train_Dec1_ML.pkl")
DDD_Train_Dec2 = pd.read_pickle("DDD_Train_Dec2_ML.pkl")
DDD_Train_Dec3 = pd.read_pickle("DDD_Train_Dec3_ML.pkl")
DDD_Train_Dec4 = pd.read_pickle("DDD_Train_Dec4_ML.pkl")
DDD_Train_Dec5 = pd.read_pickle("DDD_Train_Dec5_ML.pkl")
DDD_Train_Dec6 = pd.read_pickle("DDD_Train_Dec6_ML.pkl")
DDD_Train_Dec7 = pd.read_pickle("DDD_Train_Dec7_ML.pkl")
DDD_Train_Dec8 = pd.read_pickle("DDD_Train_Dec8_ML.pkl")
DDD_Train_Dec9 = pd.read_pickle("DDD_Train_Dec9_ML.pkl")
DDD_Train_Dec10 = pd.read_pickle("DDD_Train_Dec10_ML.pkl")

DDD_Test_Dec0 = pd.read_pickle("DDD_Test_Dec0_ML.pkl")
DDD_Test_Dec1 = pd.read_pickle("DDD_Test_Dec1_ML.pkl")
DDD_Test_Dec2 = pd.read_pickle("DDD_Test_Dec2_ML.pkl")
DDD_Test_Dec3 = pd.read_pickle("DDD_Test_Dec3_ML.pkl")
DDD_Test_Dec4 = pd.read_pickle("DDD_Test_Dec4_ML.pkl")
DDD_Test_Dec5 = pd.read_pickle("DDD_Test_Dec5_ML.pkl")
DDD_Test_Dec6 = pd.read_pickle("DDD_Test_Dec6_ML.pkl")
DDD_Test_Dec7 = pd.read_pickle("DDD_Test_Dec7_ML.pkl")
DDD_Test_Dec8 = pd.read_pickle("DDD_Test_Dec8_ML.pkl")
DDD_Test_Dec9 = pd.read_pickle("DDD_Test_Dec9_ML.pkl")
DDD_Test_Dec10 = pd.read_pickle("DDD_Test_Dec10_ML.pkl")

In [4]:
FFF_Train_Dec0 = pd.read_pickle("FFF_Train_Dec0_ML.pkl")
FFF_Train_Dec1 = pd.read_pickle("FFF_Train_Dec1_ML.pkl")
FFF_Train_Dec2 = pd.read_pickle("FFF_Train_Dec2_ML.pkl")
FFF_Train_Dec3 = pd.read_pickle("FFF_Train_Dec3_ML.pkl")
FFF_Train_Dec4 = pd.read_pickle("FFF_Train_Dec4_ML.pkl")
FFF_Train_Dec5 = pd.read_pickle("FFF_Train_Dec5_ML.pkl")
FFF_Train_Dec6 = pd.read_pickle("FFF_Train_Dec6_ML.pkl")
FFF_Train_Dec7 = pd.read_pickle("FFF_Train_Dec7_ML.pkl")
FFF_Train_Dec8 = pd.read_pickle("FFF_Train_Dec8_ML.pkl")
FFF_Train_Dec9 = pd.read_pickle("FFF_Train_Dec9_ML.pkl")
FFF_Train_Dec10 = pd.read_pickle("FFF_Train_Dec10_ML.pkl")

FFF_Test_Dec0 = pd.read_pickle("FFF_Test_Dec0_ML.pkl")
FFF_Test_Dec1 = pd.read_pickle("FFF_Test_Dec1_ML.pkl")
FFF_Test_Dec2 = pd.read_pickle("FFF_Test_Dec2_ML.pkl")
FFF_Test_Dec3 = pd.read_pickle("FFF_Test_Dec3_ML.pkl")
FFF_Test_Dec4 = pd.read_pickle("FFF_Test_Dec4_ML.pkl")
FFF_Test_Dec5 = pd.read_pickle("FFF_Test_Dec5_ML.pkl")
FFF_Test_Dec6 = pd.read_pickle("FFF_Test_Dec6_ML.pkl")
FFF_Test_Dec7 = pd.read_pickle("FFF_Test_Dec7_ML.pkl")
FFF_Test_Dec8 = pd.read_pickle("FFF_Test_Dec8_ML.pkl")
FFF_Test_Dec9 = pd.read_pickle("FFF_Test_Dec9_ML.pkl")
FFF_Test_Dec10 = pd.read_pickle("FFF_Test_Dec10_ML.pkl")

In [5]:
BBB_Train_Dec0

code_presentation         identifier  final_result  Avg_score|-23  \
0                2013B  BBB 2013B 1008675             1            0.0   
1                2013B   BBB 2013B 104054             1            0.0   
2                2013B   BBB 2013B 108377             1            0.0   
3                2013B   BBB 2013B 108589             1            0.0   
4                2013B  BBB 2013B 1098728             0            0.0   
5                2013B   BBB 2013B 109938             1            0.0   
6                2013B   BBB 2013B 110881             1            0.0   
7                2013B   BBB 2013B 116603             1            0.0   
8                2013B   BBB 2013B 117071             0            0.0   
9                2013B   BBB 2013B 120994             0            0.0   
10               2013B   BBB 2013B 123860             1            0.0   
11               2013B   BBB 2013B 126322             1            0.0   
12               2013B   BBB 2013B 126411             0            0.0   
13               2013B   BBB 2013B 133155             1            0.0   
14               2013B   BBB 2013B 133748             0            0.0   
15               2013B   BBB 2013B 142324             0            0.0   
16               2013B  BBB 2013B 1436591             1            0.0   
17               2013B   BBB 2013B 143741             1            0.0   
18               2013B   BBB 2013B 145544             1            0.0   
19               2013B   BBB 2013B 147876             0            0.0   
20               2013B  BBB 2013B 1480800             1            0.0   
21               2013B  BBB 2013B 1493476             1            0.0   
22               2013B   BBB 2013B 151697             1            0.0   
23               2013B  BBB 2013B 1521540             1            0.0   
24               2013B   BBB 2013B 152910             1            0.0   
25               2013B   BBB 2013B 152929             1            0.0   
26               2013B   BBB 2013B 153212             1            0.0   
27               2013B   BBB 2013B 154027             1            0.0   
28               2013B   BBB 2013B 154125             0            0.0   
29               2013B   BBB 2013B 154540             1            0.0   
...                ...                ...           ...            ...   
3829             2014B   BBB 2014B 635136             1            0.0   
3830             2014B   BBB 2014B 635173             1            0.0   
3831             2014B   BBB 2014B 635228             1            0.0   
3832             2014B   BBB 2014B 635230             1            0.0   
3833             2014B   BBB 2014B 635241             1            0.0   
3834             2014B   BBB 2014B 635244             1            0.0   
3835             2014B   BBB 2014B 635246             0            0.0   
3836             2014B   BBB 2014B 635247             1            0.0   
3837             2014B   BBB 2014B 635432             0            0.0   
3838             2014B   BBB 2014B 635433             1            0.0   
3839             2014B   BBB 2014B 635435             1            0.0   
3840             2014B   BBB 2014B 635473             0            0.0   
3841             2014B   BBB 2014B 635591             1            0.0   
3842             2014B   BBB 2014B 635755             1            0.0   
3843             2014B   BBB 2014B 635761             1            0.0   
3844             2014B   BBB 2014B 635764             1            0.0   
3845             2014B   BBB 2014B 635771             1            0.0   
3846             2014B   BBB 2014B 635773             1            0.0   
3847             2014B   BBB 2014B 635774             1            0.0   
3848             2014B   BBB 2014B 635788             1            0.0   
3849             2014B    BBB 2014B 63721             1            0.0   
3850             2014B    BBB 2014B 64275             1            0.0   
3851     

In [6]:
from sklearn.model_selection import train_test_split, RandomizedSearchCV, GridSearchCV
from sklearn.naive_bayes import GaussianNB
from sklearn.metrics import accuracy_score, classification_report, confusion_matrix

### Course BBB NB

#### BBB Decile 0 NB

In [7]:
X_train = BBB_Train_Dec0.drop(["code_presentation","identifier","final_result"],axis=1)
y_train = BBB_Train_Dec0["final_result"]
X_test = BBB_Test_Dec0.drop(["code_presentation","identifier","final_result"],axis=1)
y_test = BBB_Test_Dec0["final_result"]

In [8]:
base_model = GaussianNB()
base_model.fit(X_train, y_train)

predictions = base_model.predict(X_test)

print(classification_report(y_test,predictions))
print(accuracy_score(y_test, predictions))
print(confusion_matrix(y_test, predictions))

              precision    recall  f1-score   support

           0       0.24      1.00      0.39       369
           1       0.88      0.01      0.01      1152

   micro avg       0.25      0.25      0.25      1521
   macro avg       0.56      0.50      0.20      1521
weighted avg       0.72      0.25      0.10      1521

0.2465483234714004
[[ 368    1]
 [1145    7]]


#### BBB Decile 1 NB

In [9]:
X_train = BBB_Train_Dec1.drop(["code_presentation","identifier","final_result"],axis=1)
y_train = BBB_Train_Dec1["final_result"]
X_test = BBB_Test_Dec1.drop(["code_presentation","identifier","final_result"],axis=1)
y_test = BBB_Test_Dec1["final_result"]

In [10]:
base_model = GaussianNB()
base_model.fit(X_train, y_train)

predictions = base_model.predict(X_test)

print(classification_report(y_test,predictions))
print(accuracy_score(y_test, predictions))
print(confusion_matrix(y_test, predictions))

              precision    recall  f1-score   support

           0       0.25      0.99      0.39       369
           1       0.87      0.03      0.06      1152

   micro avg       0.26      0.26      0.26      1521
   macro avg       0.56      0.51      0.22      1521
weighted avg       0.72      0.26      0.14      1521

0.26101249178172253
[[ 364    5]
 [1119   33]]


#### BBB Decile 2 NB

In [11]:
X_train = BBB_Train_Dec2.drop(["code_presentation","identifier","final_result"],axis=1)
y_train = BBB_Train_Dec2["final_result"]
X_test = BBB_Test_Dec2.drop(["code_presentation","identifier","final_result"],axis=1)
y_test = BBB_Test_Dec2["final_result"]

In [12]:
base_model = GaussianNB()
base_model.fit(X_train, y_train)

predictions = base_model.predict(X_test)

print(classification_report(y_test,predictions))
print(accuracy_score(y_test, predictions))
print(confusion_matrix(y_test, predictions))

              precision    recall  f1-score   support

           0       0.25      0.99      0.39       369
           1       0.89      0.03      0.05      1152

   micro avg       0.26      0.26      0.26      1521
   macro avg       0.57      0.51      0.22      1521
weighted avg       0.73      0.26      0.14      1521

0.26101249178172253
[[ 365    4]
 [1120   32]]


#### BBB Decile 3 NB

In [13]:
X_train = BBB_Train_Dec3.drop(["code_presentation","identifier","final_result"],axis=1)
y_train = BBB_Train_Dec3["final_result"]
X_test = BBB_Test_Dec3.drop(["code_presentation","identifier","final_result"],axis=1)
y_test = BBB_Test_Dec3["final_result"]

In [14]:
base_model = GaussianNB()
base_model.fit(X_train, y_train)

predictions = base_model.predict(X_test)

print(classification_report(y_test,predictions))
print(accuracy_score(y_test, predictions))
print(confusion_matrix(y_test, predictions))

              precision    recall  f1-score   support

           0       0.24      0.99      0.39       369
           1       0.90      0.02      0.03      1152

   micro avg       0.25      0.25      0.25      1521
   macro avg       0.57      0.51      0.21      1521
weighted avg       0.74      0.25      0.12      1521

0.25312294543063774
[[ 367    2]
 [1134   18]]


#### BBB Decile 4 NB

In [15]:
X_train = BBB_Train_Dec4.drop(["code_presentation","identifier","final_result"],axis=1)
y_train = BBB_Train_Dec4["final_result"]
X_test = BBB_Test_Dec4.drop(["code_presentation","identifier","final_result"],axis=1)
y_test = BBB_Test_Dec4["final_result"]

In [16]:
base_model = GaussianNB()
base_model.fit(X_train, y_train)

predictions = base_model.predict(X_test)

print(classification_report(y_test,predictions))
print(accuracy_score(y_test, predictions))
print(confusion_matrix(y_test, predictions))

              precision    recall  f1-score   support

           0       0.28      0.96      0.44       369
           1       0.94      0.22      0.35      1152

   micro avg       0.40      0.40      0.40      1521
   macro avg       0.61      0.59      0.40      1521
weighted avg       0.78      0.40      0.37      1521

0.3977646285338593
[[353  16]
 [900 252]]


#### BBB Decile 5 NB

In [17]:
X_train = BBB_Train_Dec5.drop(["code_presentation","identifier","final_result"],axis=1)
y_train = BBB_Train_Dec5["final_result"]
X_test = BBB_Test_Dec5.drop(["code_presentation","identifier","final_result"],axis=1)
y_test = BBB_Test_Dec5["final_result"]

In [18]:
base_model = GaussianNB()
base_model.fit(X_train, y_train)

predictions = base_model.predict(X_test)

print(classification_report(y_test,predictions))
print(accuracy_score(y_test, predictions))
print(confusion_matrix(y_test, predictions))

              precision    recall  f1-score   support

           0       0.31      0.88      0.46       369
           1       0.91      0.39      0.54      1152

   micro avg       0.51      0.51      0.51      1521
   macro avg       0.61      0.63      0.50      1521
weighted avg       0.76      0.51      0.52      1521

0.5069033530571992
[[324  45]
 [705 447]]


#### BBB Decile 6 NB

In [19]:
X_train = BBB_Train_Dec6.drop(["code_presentation","identifier","final_result"],axis=1)
y_train = BBB_Train_Dec6["final_result"]
X_test = BBB_Test_Dec6.drop(["code_presentation","identifier","final_result"],axis=1)
y_test = BBB_Test_Dec6["final_result"]

In [20]:
base_model = GaussianNB()
base_model.fit(X_train, y_train)

predictions = base_model.predict(X_test)

print(classification_report(y_test,predictions))
print(accuracy_score(y_test, predictions))
print(confusion_matrix(y_test, predictions))

              precision    recall  f1-score   support

           0       0.35      0.79      0.48       369
           1       0.88      0.52      0.66      1152

   micro avg       0.59      0.59      0.59      1521
   macro avg       0.62      0.66      0.57      1521
weighted avg       0.75      0.59      0.62      1521

0.5877712031558185
[[290  79]
 [548 604]]


#### BBB Decile 7 NB

In [21]:
X_train = BBB_Train_Dec7.drop(["code_presentation","identifier","final_result"],axis=1)
y_train = BBB_Train_Dec7["final_result"]
X_test = BBB_Test_Dec7.drop(["code_presentation","identifier","final_result"],axis=1)
y_test = BBB_Test_Dec7["final_result"]

In [22]:
base_model = GaussianNB()
base_model.fit(X_train, y_train)

predictions = base_model.predict(X_test)

print(classification_report(y_test,predictions))
print(accuracy_score(y_test, predictions))
print(confusion_matrix(y_test, predictions))

              precision    recall  f1-score   support

           0       0.36      0.80      0.50       369
           1       0.90      0.55      0.68      1152

   micro avg       0.61      0.61      0.61      1521
   macro avg       0.63      0.68      0.59      1521
weighted avg       0.77      0.61      0.64      1521

0.6107823800131492
[[296  73]
 [519 633]]


#### BBB Decile 8 NB

In [23]:
X_train = BBB_Train_Dec8.drop(["code_presentation","identifier","final_result"],axis=1)
y_train = BBB_Train_Dec8["final_result"]
X_test = BBB_Test_Dec8.drop(["code_presentation","identifier","final_result"],axis=1)
y_test = BBB_Test_Dec8["final_result"]

In [24]:
base_model = GaussianNB()
base_model.fit(X_train, y_train)

predictions = base_model.predict(X_test)

print(classification_report(y_test,predictions))
print(accuracy_score(y_test, predictions))
print(confusion_matrix(y_test, predictions))

              precision    recall  f1-score   support

           0       0.38      0.83      0.52       369
           1       0.91      0.57      0.70      1152

   micro avg       0.63      0.63      0.63      1521
   macro avg       0.65      0.70      0.61      1521
weighted avg       0.78      0.63      0.66      1521

0.6318211702827088
[[305  64]
 [496 656]]


#### BBB Decile 9 NB

In [25]:
X_train = BBB_Train_Dec9.drop(["code_presentation","identifier","final_result"],axis=1)
y_train = BBB_Train_Dec9["final_result"]
X_test = BBB_Test_Dec9.drop(["code_presentation","identifier","final_result"],axis=1)
y_test = BBB_Test_Dec9["final_result"]

In [26]:
base_model = GaussianNB()
base_model.fit(X_train, y_train)

predictions = base_model.predict(X_test)

print(classification_report(y_test,predictions))
print(accuracy_score(y_test, predictions))
print(confusion_matrix(y_test, predictions))

              precision    recall  f1-score   support

           0       0.40      0.83      0.54       369
           1       0.92      0.60      0.73      1152

   micro avg       0.66      0.66      0.66      1521
   macro avg       0.66      0.72      0.63      1521
weighted avg       0.79      0.66      0.68      1521

0.6561472715318869
[[308  61]
 [462 690]]


#### BBB Decile 10 NB

In [27]:
X_train = BBB_Train_Dec10.drop(["code_presentation","identifier","final_result"],axis=1)
y_train = BBB_Train_Dec10["final_result"]
X_test = BBB_Test_Dec10.drop(["code_presentation","identifier","final_result"],axis=1)
y_test = BBB_Test_Dec10["final_result"]

In [28]:
base_model = GaussianNB()
base_model.fit(X_train, y_train)

predictions = base_model.predict(X_test)

print(classification_report(y_test,predictions))
print(accuracy_score(y_test, predictions))
print(confusion_matrix(y_test, predictions))

              precision    recall  f1-score   support

           0       0.41      0.84      0.55       369
           1       0.92      0.61      0.74      1152

   micro avg       0.67      0.67      0.67      1521
   macro avg       0.67      0.73      0.64      1521
weighted avg       0.80      0.67      0.69      1521

0.6686390532544378
[[311  58]
 [446 706]]


### Course DDD NB

#### DDD Decile 0 NB

In [29]:
X_train = DDD_Train_Dec0.drop(["code_presentation","identifier","final_result"],axis=1)
y_train = DDD_Train_Dec0["final_result"]
X_test = DDD_Test_Dec0.drop(["code_presentation","identifier","final_result"],axis=1)
y_test = DDD_Test_Dec0["final_result"]

In [30]:
base_model = GaussianNB()
base_model.fit(X_train, y_train)

predictions = base_model.predict(X_test)

print(classification_report(y_test,predictions))
print(accuracy_score(y_test, predictions))
print(confusion_matrix(y_test, predictions))

              precision    recall  f1-score   support

           0       0.31      1.00      0.47       358
           1       0.00      0.00      0.00       792

   micro avg       0.31      0.31      0.31      1150
   macro avg       0.16      0.50      0.24      1150
weighted avg       0.10      0.31      0.15      1150

0.31130434782608696
[[358   0]
 [792   0]]


C:\Users\Chris\Anaconda3\lib\site-packages\sklearn\metrics\classification.py:1143: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples.
  'precision', 'predicted', average, warn_for)


#### DDD Decile 1 NB

In [31]:
X_train = DDD_Train_Dec1.drop(["code_presentation","identifier","final_result"],axis=1)
y_train = DDD_Train_Dec1["final_result"]
X_test = DDD_Test_Dec1.drop(["code_presentation","identifier","final_result"],axis=1)
y_test = DDD_Test_Dec1["final_result"]

In [32]:
base_model = GaussianNB()
base_model.fit(X_train, y_train)

predictions = base_model.predict(X_test)

print(classification_report(y_test,predictions))
print(accuracy_score(y_test, predictions))
print(confusion_matrix(y_test, predictions))

              precision    recall  f1-score   support

           0       0.31      1.00      0.48       358
           1       0.89      0.01      0.02       792

   micro avg       0.32      0.32      0.32      1150
   macro avg       0.60      0.50      0.25      1150
weighted avg       0.71      0.32      0.16      1150

0.3173913043478261
[[357   1]
 [784   8]]


#### DDD Decile 2 NB

In [33]:
X_train = DDD_Train_Dec2.drop(["code_presentation","identifier","final_result"],axis=1)
y_train = DDD_Train_Dec2["final_result"]
X_test = DDD_Test_Dec2.drop(["code_presentation","identifier","final_result"],axis=1)
y_test = DDD_Test_Dec2["final_result"]

In [34]:
base_model = GaussianNB()
base_model.fit(X_train, y_train)

predictions = base_model.predict(X_test)

print(classification_report(y_test,predictions))
print(accuracy_score(y_test, predictions))
print(confusion_matrix(y_test, predictions))

              precision    recall  f1-score   support

           0       0.33      0.99      0.50       358
           1       0.96      0.11      0.19       792

   micro avg       0.38      0.38      0.38      1150
   macro avg       0.64      0.55      0.35      1150
weighted avg       0.76      0.38      0.29      1150

0.38173913043478264
[[354   4]
 [707  85]]


#### DDD Decile 3 NB

In [35]:
X_train = DDD_Train_Dec3.drop(["code_presentation","identifier","final_result"],axis=1)
y_train = DDD_Train_Dec3["final_result"]
X_test = DDD_Test_Dec3.drop(["code_presentation","identifier","final_result"],axis=1)
y_test = DDD_Test_Dec3["final_result"]

In [36]:
base_model = GaussianNB()
base_model.fit(X_train, y_train)

predictions = base_model.predict(X_test)

print(classification_report(y_test,predictions))
print(accuracy_score(y_test, predictions))
print(confusion_matrix(y_test, predictions))

              precision    recall  f1-score   support

           0       0.37      0.95      0.53       358
           1       0.93      0.27      0.41       792

   micro avg       0.48      0.48      0.48      1150
   macro avg       0.65      0.61      0.47      1150
weighted avg       0.75      0.48      0.45      1150

0.48
[[341  17]
 [581 211]]


#### DDD Decile 4 NB

In [37]:
X_train = DDD_Train_Dec4.drop(["code_presentation","identifier","final_result"],axis=1)
y_train = DDD_Train_Dec4["final_result"]
X_test = DDD_Test_Dec4.drop(["code_presentation","identifier","final_result"],axis=1)
y_test = DDD_Test_Dec4["final_result"]

In [38]:
base_model = GaussianNB()
base_model.fit(X_train, y_train)

predictions = base_model.predict(X_test)

print(classification_report(y_test,predictions))
print(accuracy_score(y_test, predictions))
print(confusion_matrix(y_test, predictions))

              precision    recall  f1-score   support

           0       0.57      0.70      0.63       358
           1       0.85      0.77      0.81       792

   micro avg       0.75      0.75      0.75      1150
   macro avg       0.71      0.73      0.72      1150
weighted avg       0.76      0.75      0.75      1150

0.7452173913043478
[[251 107]
 [186 606]]


#### DDD Decile 5 NB

In [39]:
X_train = DDD_Train_Dec5.drop(["code_presentation","identifier","final_result"],axis=1)
y_train = DDD_Train_Dec5["final_result"]
X_test = DDD_Test_Dec5.drop(["code_presentation","identifier","final_result"],axis=1)
y_test = DDD_Test_Dec5["final_result"]

In [40]:
base_model = GaussianNB()
base_model.fit(X_train, y_train)

predictions = base_model.predict(X_test)

print(classification_report(y_test,predictions))
print(accuracy_score(y_test, predictions))
print(confusion_matrix(y_test, predictions))

              precision    recall  f1-score   support

           0       0.68      0.63      0.66       358
           1       0.84      0.87      0.85       792

   micro avg       0.79      0.79      0.79      1150
   macro avg       0.76      0.75      0.75      1150
weighted avg       0.79      0.79      0.79      1150

0.7930434782608695
[[226 132]
 [106 686]]


#### DDD Decile 6 NB

In [41]:
X_train = DDD_Train_Dec6.drop(["code_presentation","identifier","final_result"],axis=1)
y_train = DDD_Train_Dec6["final_result"]
X_test = DDD_Test_Dec6.drop(["code_presentation","identifier","final_result"],axis=1)
y_test = DDD_Test_Dec6["final_result"]

In [42]:
base_model = GaussianNB()
base_model.fit(X_train, y_train)

predictions = base_model.predict(X_test)

print(classification_report(y_test,predictions))
print(accuracy_score(y_test, predictions))
print(confusion_matrix(y_test, predictions))

              precision    recall  f1-score   support

           0       0.71      0.61      0.66       358
           1       0.84      0.89      0.86       792

   micro avg       0.80      0.80      0.80      1150
   macro avg       0.78      0.75      0.76      1150
weighted avg       0.80      0.80      0.80      1150

0.8034782608695652
[[220 138]
 [ 88 704]]


#### DDD Decile 7 NB

In [43]:
X_train = DDD_Train_Dec7.drop(["code_presentation","identifier","final_result"],axis=1)
y_train = DDD_Train_Dec7["final_result"]
X_test = DDD_Test_Dec7.drop(["code_presentation","identifier","final_result"],axis=1)
y_test = DDD_Test_Dec7["final_result"]

In [44]:
base_model = GaussianNB()
base_model.fit(X_train, y_train)

predictions = base_model.predict(X_test)

print(classification_report(y_test,predictions))
print(accuracy_score(y_test, predictions))
print(confusion_matrix(y_test, predictions))

              precision    recall  f1-score   support

           0       0.77      0.61      0.68       358
           1       0.84      0.92      0.88       792

   micro avg       0.82      0.82      0.82      1150
   macro avg       0.80      0.76      0.78      1150
weighted avg       0.82      0.82      0.82      1150

0.8217391304347826
[[218 140]
 [ 65 727]]


#### DDD Decile 8 NB

In [45]:
X_train = DDD_Train_Dec8.drop(["code_presentation","identifier","final_result"],axis=1)
y_train = DDD_Train_Dec8["final_result"]
X_test = DDD_Test_Dec8.drop(["code_presentation","identifier","final_result"],axis=1)
y_test = DDD_Test_Dec8["final_result"]

In [46]:
base_model = GaussianNB()
base_model.fit(X_train, y_train)

predictions = base_model.predict(X_test)

print(classification_report(y_test,predictions))
print(accuracy_score(y_test, predictions))
print(confusion_matrix(y_test, predictions))

              precision    recall  f1-score   support

           0       0.79      0.58      0.67       358
           1       0.83      0.93      0.88       792

   micro avg       0.82      0.82      0.82      1150
   macro avg       0.81      0.76      0.77      1150
weighted avg       0.82      0.82      0.81      1150

0.8217391304347826
[[207 151]
 [ 54 738]]


#### DDD Decile 9 NB

In [47]:
X_train = DDD_Train_Dec9.drop(["code_presentation","identifier","final_result"],axis=1)
y_train = DDD_Train_Dec9["final_result"]
X_test = DDD_Test_Dec9.drop(["code_presentation","identifier","final_result"],axis=1)
y_test = DDD_Test_Dec9["final_result"]

In [48]:
base_model = GaussianNB()
base_model.fit(X_train, y_train)

predictions = base_model.predict(X_test)

print(classification_report(y_test,predictions))
print(accuracy_score(y_test, predictions))
print(confusion_matrix(y_test, predictions))

              precision    recall  f1-score   support

           0       0.81      0.57      0.67       358
           1       0.83      0.94      0.88       792

   micro avg       0.82      0.82      0.82      1150
   macro avg       0.82      0.75      0.77      1150
weighted avg       0.82      0.82      0.81      1150

0.8243478260869566
[[204 154]
 [ 48 744]]


#### DDD Decile 10 NB

In [49]:
X_train = DDD_Train_Dec10.drop(["code_presentation","identifier","final_result"],axis=1)
y_train = DDD_Train_Dec10["final_result"]
X_test = DDD_Test_Dec10.drop(["code_presentation","identifier","final_result"],axis=1)
y_test = DDD_Test_Dec10["final_result"]

In [50]:
base_model = GaussianNB()
base_model.fit(X_train, y_train)

predictions = base_model.predict(X_test)

print(classification_report(y_test,predictions))
print(accuracy_score(y_test, predictions))
print(confusion_matrix(y_test, predictions))

              precision    recall  f1-score   support

           0       0.80      0.64      0.71       358
           1       0.85      0.93      0.89       792

   micro avg       0.84      0.84      0.84      1150
   macro avg       0.82      0.78      0.80      1150
weighted avg       0.83      0.84      0.83      1150

0.837391304347826
[[228 130]
 [ 57 735]]


### Course FFF NB

#### FFF Decile 0 NB

In [51]:
X_train = FFF_Train_Dec0.drop(["code_presentation","identifier","final_result"],axis=1)
y_train = FFF_Train_Dec0["final_result"]
X_test = FFF_Test_Dec0.drop(["code_presentation","identifier","final_result"],axis=1)
y_test = FFF_Test_Dec0["final_result"]

In [52]:
base_model = GaussianNB()
base_model.fit(X_train, y_train)

predictions = base_model.predict(X_test)

print(classification_report(y_test,predictions))
print(accuracy_score(y_test, predictions))
print(confusion_matrix(y_test, predictions))

              precision    recall  f1-score   support

           0       0.27      0.93      0.42       387
           1       0.86      0.15      0.25      1117

   micro avg       0.35      0.35      0.35      1504
   macro avg       0.57      0.54      0.34      1504
weighted avg       0.71      0.35      0.29      1504

0.3484042553191489
[[361  26]
 [954 163]]


#### FFF Decile 1 NB

In [53]:
X_train = FFF_Train_Dec1.drop(["code_presentation","identifier","final_result"],axis=1)
y_train = FFF_Train_Dec1["final_result"]
X_test = FFF_Test_Dec1.drop(["code_presentation","identifier","final_result"],axis=1)
y_test = FFF_Test_Dec1["final_result"]

In [54]:
base_model = GaussianNB()
base_model.fit(X_train, y_train)

predictions = base_model.predict(X_test)

print(classification_report(y_test,predictions))
print(accuracy_score(y_test, predictions))
print(confusion_matrix(y_test, predictions))

              precision    recall  f1-score   support

           0       0.31      0.88      0.46       387
           1       0.88      0.31      0.46      1117

   micro avg       0.46      0.46      0.46      1504
   macro avg       0.60      0.60      0.46      1504
weighted avg       0.74      0.46      0.46      1504

0.45811170212765956
[[341  46]
 [769 348]]


#### FFF Decile 2 NB

In [55]:
X_train = FFF_Train_Dec2.drop(["code_presentation","identifier","final_result"],axis=1)
y_train = FFF_Train_Dec2["final_result"]
X_test = FFF_Test_Dec2.drop(["code_presentation","identifier","final_result"],axis=1)
y_test = FFF_Test_Dec2["final_result"]

In [56]:
base_model = GaussianNB()
base_model.fit(X_train, y_train)

predictions = base_model.predict(X_test)

print(classification_report(y_test,predictions))
print(accuracy_score(y_test, predictions))
print(confusion_matrix(y_test, predictions))

              precision    recall  f1-score   support

           0       0.43      0.74      0.54       387
           1       0.88      0.66      0.75      1117

   micro avg       0.68      0.68      0.68      1504
   macro avg       0.65      0.70      0.65      1504
weighted avg       0.76      0.68      0.70      1504

0.6795212765957447
[[286 101]
 [381 736]]


#### FFF Decile 3 NB

In [57]:
X_train = FFF_Train_Dec3.drop(["code_presentation","identifier","final_result"],axis=1)
y_train = FFF_Train_Dec3["final_result"]
X_test = FFF_Test_Dec3.drop(["code_presentation","identifier","final_result"],axis=1)
y_test = FFF_Test_Dec3["final_result"]

In [58]:
base_model = GaussianNB()
base_model.fit(X_train, y_train)

predictions = base_model.predict(X_test)

print(classification_report(y_test,predictions))
print(accuracy_score(y_test, predictions))
print(confusion_matrix(y_test, predictions))

              precision    recall  f1-score   support

           0       0.55      0.67      0.60       387
           1       0.88      0.81      0.84      1117

   micro avg       0.77      0.77      0.77      1504
   macro avg       0.71      0.74      0.72      1504
weighted avg       0.79      0.77      0.78      1504

0.7719414893617021
[[258 129]
 [214 903]]


#### FFF Decile 4 NB

In [59]:
X_train = FFF_Train_Dec4.drop(["code_presentation","identifier","final_result"],axis=1)
y_train = FFF_Train_Dec4["final_result"]
X_test = FFF_Test_Dec4.drop(["code_presentation","identifier","final_result"],axis=1)
y_test = FFF_Test_Dec4["final_result"]

In [60]:
base_model = GaussianNB()
base_model.fit(X_train, y_train)

predictions = base_model.predict(X_test)

print(classification_report(y_test,predictions))
print(accuracy_score(y_test, predictions))
print(confusion_matrix(y_test, predictions))

              precision    recall  f1-score   support

           0       0.58      0.65      0.61       387
           1       0.87      0.84      0.86      1117

   micro avg       0.79      0.79      0.79      1504
   macro avg       0.73      0.74      0.73      1504
weighted avg       0.80      0.79      0.79      1504

0.7892287234042553
[[250 137]
 [180 937]]


#### FFF Decile 5 NB

In [61]:
X_train = FFF_Train_Dec5.drop(["code_presentation","identifier","final_result"],axis=1)
y_train = FFF_Train_Dec5["final_result"]
X_test = FFF_Test_Dec5.drop(["code_presentation","identifier","final_result"],axis=1)
y_test = FFF_Test_Dec5["final_result"]

In [62]:
base_model = GaussianNB()
base_model.fit(X_train, y_train)

predictions = base_model.predict(X_test)

print(classification_report(y_test,predictions))
print(accuracy_score(y_test, predictions))
print(confusion_matrix(y_test, predictions))

              precision    recall  f1-score   support

           0       0.62      0.66      0.64       387
           1       0.88      0.86      0.87      1117

   micro avg       0.81      0.81      0.81      1504
   macro avg       0.75      0.76      0.75      1504
weighted avg       0.81      0.81      0.81      1504

0.807845744680851
[[257 130]
 [159 958]]


#### FFF Decile 6 NB

In [63]:
X_train = FFF_Train_Dec6.drop(["code_presentation","identifier","final_result"],axis=1)
y_train = FFF_Train_Dec6["final_result"]
X_test = FFF_Test_Dec6.drop(["code_presentation","identifier","final_result"],axis=1)
y_test = FFF_Test_Dec6["final_result"]

In [64]:
base_model = GaussianNB()
base_model.fit(X_train, y_train)

predictions = base_model.predict(X_test)

print(classification_report(y_test,predictions))
print(accuracy_score(y_test, predictions))
print(confusion_matrix(y_test, predictions))

              precision    recall  f1-score   support

           0       0.66      0.70      0.68       387
           1       0.89      0.88      0.89      1117

   micro avg       0.83      0.83      0.83      1504
   macro avg       0.78      0.79      0.78      1504
weighted avg       0.83      0.83      0.83      1504

0.8311170212765957
[[271 116]
 [138 979]]


#### FFF Decile 7 NB

In [65]:
X_train = FFF_Train_Dec7.drop(["code_presentation","identifier","final_result"],axis=1)
y_train = FFF_Train_Dec7["final_result"]
X_test = FFF_Test_Dec7.drop(["code_presentation","identifier","final_result"],axis=1)
y_test = FFF_Test_Dec7["final_result"]

In [66]:
base_model = GaussianNB()
base_model.fit(X_train, y_train)

predictions = base_model.predict(X_test)

print(classification_report(y_test,predictions))
print(accuracy_score(y_test, predictions))
print(confusion_matrix(y_test, predictions))

              precision    recall  f1-score   support

           0       0.67      0.71      0.69       387
           1       0.90      0.88      0.89      1117

   micro avg       0.84      0.84      0.84      1504
   macro avg       0.78      0.80      0.79      1504
weighted avg       0.84      0.84      0.84      1504

0.8357712765957447
[[276 111]
 [136 981]]


#### FFF Decile 8 NB

In [67]:
X_train = FFF_Train_Dec8.drop(["code_presentation","identifier","final_result"],axis=1)
y_train = FFF_Train_Dec8["final_result"]
X_test = FFF_Test_Dec8.drop(["code_presentation","identifier","final_result"],axis=1)
y_test = FFF_Test_Dec8["final_result"]

In [68]:
base_model = GaussianNB()
base_model.fit(X_train, y_train)

predictions = base_model.predict(X_test)

print(classification_report(y_test,predictions))
print(accuracy_score(y_test, predictions))
print(confusion_matrix(y_test, predictions))

              precision    recall  f1-score   support

           0       0.68      0.72      0.70       387
           1       0.90      0.88      0.89      1117

   micro avg       0.84      0.84      0.84      1504
   macro avg       0.79      0.80      0.79      1504
weighted avg       0.84      0.84      0.84      1504

0.839095744680851
[[278 109]
 [133 984]]


#### FFF Decile 9 NB

In [69]:
X_train = FFF_Train_Dec9.drop(["code_presentation","identifier","final_result"],axis=1)
y_train = FFF_Train_Dec9["final_result"]
X_test = FFF_Test_Dec9.drop(["code_presentation","identifier","final_result"],axis=1)
y_test = FFF_Test_Dec9["final_result"]

In [70]:
base_model = GaussianNB()
base_model.fit(X_train, y_train)

predictions = base_model.predict(X_test)

print(classification_report(y_test,predictions))
print(accuracy_score(y_test, predictions))
print(confusion_matrix(y_test, predictions))

              precision    recall  f1-score   support

           0       0.71      0.75      0.73       387
           1       0.91      0.90      0.90      1117

   micro avg       0.86      0.86      0.86      1504
   macro avg       0.81      0.82      0.82      1504
weighted avg       0.86      0.86      0.86      1504

0.8583776595744681
[[ 291   96]
 [ 117 1000]]


#### FFF Decile 10 NB

In [71]:
X_train = FFF_Train_Dec10.drop(["code_presentation","identifier","final_result"],axis=1)
y_train = FFF_Train_Dec10["final_result"]
X_test = FFF_Test_Dec10.drop(["code_presentation","identifier","final_result"],axis=1)
y_test = FFF_Test_Dec10["final_result"]

In [72]:
base_model = GaussianNB()
base_model.fit(X_train, y_train)

predictions = base_model.predict(X_test)

print(classification_report(y_test,predictions))
print(accuracy_score(y_test, predictions))
print(confusion_matrix(y_test, predictions))

              precision    recall  f1-score   support

           0       0.79      0.76      0.77       387
           1       0.92      0.93      0.92      1117

   micro avg       0.88      0.88      0.88      1504
   macro avg       0.85      0.84      0.85      1504
weighted avg       0.88      0.88      0.88      1504

0.8843085106382979
[[ 293   94]
 [  80 1037]]
